version: '3.8'

services:
  app:
    image: app
    container_name: app
    hostname: app
    build:
      context: 'client'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - shared-network

    restart: unless-stopped

  api:
    image: api
    container_name: api
    hostname: api
    build:
      context: 'server'
      dockerfile: Dockerfile

    ports:
      - 9000:9000
    
    environment:
      - ATLAS_URL=mongodb+srv://dbUser:Tictactoe@tictactoecluster.av69y.mongodb.net/?retryWrites=true&w=majority
      - JWT_SECRET=secrettictactoe
      - CLIENT_ORIGIN=https://tictacground.space

    networks:
      - shared-network
    
    restart: unless-stopped

  nginx:
    image: nginx:1.22.0
    container_name: nginx
    ports:
      - 80:80
      - 443:443

    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot

    command: /bin/sh -c "nginx -g 'daemon off;'"

    depends_on:
      app:
        condition: service_started
      api:
        condition: service_started

    networks:
      - shared-network

networks:
  shared-network:
