version: '3.8'

services:
  app:
    image: app
    container_name: app
    build:
      context: 'client'
      dockerfile: Dockerfile
    command: yarn start
    ports:
      - 3000:3000
    networks:
      - shared-network

    restart: unless-stopped

  api:
    image: api
    container_name: api
    build:
      context: 'server'
      dockerfile: Dockerfile

    command: yarn start
    ports:
      - 9000:9000
    
    environment:
      - ATLAS_URL=mongodb+srv://dbUser:Tictactoe@tictactoecluster.av69y.mongodb.net/?retryWrites=true&w=majority
      - JWT_SECRET=secrettictactoe
      - CLIENT_ORIGIN=https://tictacground.space

    networks:
      - shared-network
    
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80

    volumes:
      - ./nginx/cert/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot

    command: /bin/sh -c "nginx -g 'daemon off;'"

    depends_on:
      app:
        condition: service_started

    networks:
      - shared-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email khsieuthisach@khsieuthisach.online --agree-tos --no-eff-email -d khsieuthisach.online -d www.khsieuthisach.online
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot

    depends_on:
      nginx:
        condition: service_started

networks:
  shared-network:
